export const PALLET_WIDTH = 320;

export const CANVAS_SIZE_MULTIPLIER = 2;

export const BAR_WIDTH = 25;
export const BAR_HEIGHT = 144;

export const BAR_CANVAS_WIDTH = BAR_WIDTH * CANVAS_SIZE_MULTIPLIER;
export const BAR_CANVAS_HEIGHT = BAR_HEIGHT * CANVAS_SIZE_MULTIPLIER;
